echo '{'
echo '  "weights": [ 0.1, 0.5, 1.0 ],'
echo '  "inputs_from_weights": true,'
echo '  "min_threshold": -1,'
echo '  "max_threshold": 1,'
echo '  "min_potential": -1,'
echo '  "max_delay": 5,'
echo '  "discrete": false'
echo '}'
