echo '      { "discrete": true,'
echo '        "fire_like_ravens": false,'
echo '        "leak_mode": "all",'
echo '        "max_delay": 15,'
echo '        "max_threshold": 7.0,'
echo '        "max_weight": 1.0,'
echo '        "min_potential": 0.0,'
echo '        "min_threshold": 1.0,'
echo '        "min_weight": -1.0,'
echo '        "run_time_inclusive": false,'
echo '        "spike_value_factor": 1.0,'
echo '        "threshold_inclusive": true}'
